version: "3.8"

services:
  website:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      target: website
    ports:
      - 80:3000
    volumes:
      - ./:/var/www/html/website:rw

