version: "3.8"

networks:
  school_net:
    name: databases_db_net
  nginx-proxy-net:
    name: nginx-proxy-manager_default

services:
  lla_site:
    container_name: lla_site
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      target: website
    ports:
      - 3000
    volumes:
      - ./:/var/www/html/website:rw
    networks:
      - school_net
      - nginx-proxy-net
